# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    fotos_perfil_directory: '%kernel.project_dir%/public/uploads/fotos_perfil'
    archivos_tareas_directory: '%kernel.project_dir%/public/uploads/tareas'
    uploads_directory: '%kernel.project_dir%/public/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Añadir configuración específica para el controlador
    App\Controller\Api\ClaseController:
        tags: ['controller.service_arguments']
        autowire: true

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%fotos_perfil_directory%'

    # Configuración manual para Knp\Snappy\Pdf si usas la clase directamente
    Knp\Snappy\Pdf:
        public: true
        bind:
            $binary: '%env(WKHTMLTOPDF_PATH)%'
            $options:
                enable-local-file-access: true
                encoding: UTF-8
                page-size: A4
                margin-top: '10'
                margin-right: '10'
                margin-bottom: '10'
                margin-left: '10'
                images: true
                javascript-delay: 1000
                lowquality: true

    App\Controller\ClaseExportController:
        tags: ['controller.service_arguments']
        autowire: true

    Symfony\Component\Ldap\Ldap:
        factory: ['Symfony\Component\Ldap\Ldap', 'create']
        arguments:
            $adapter: 'ext_ldap'
        calls:
            - method: connect
              arguments:
                  - host: '%env(LDAP_HOST)%'
                    port: '%env(LDAP_PORT)%'
                    encryption: 'none'
                    options:
                        protocol_version: 3
                        referrals: false

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
