apiVersion: apps/v1
kind: Deployment
metadata:
  name: aulasync-ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aulasync-ldap
  template:
    metadata:
      labels:
        app: aulasync-ldap
    spec:
      containers:
      - name: aulasync-ldap
        image: ferminromero/aulasync-ldap:latest
        ports:
        - containerPort: 389
        - containerPort: 636
        env:
        - name: LDAP_ORGANISATION
          value: "Aulasync"
        - name: LDAP_DOMAIN
          value: "aulasync.work.gd"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: aulasync-ldap
spec:
  type: ClusterIP
  ports:
    - port: 389
      targetPort: 389
      name: ldap
    - port: 636
      targetPort: 636
      name: ldaps
  selector:
    app: aulasync-ldap