apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ferminromero/aulasync-back:latest
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "prod"
        - name: APP_DEBUG
          value: "1"
        - name: CORS_ALLOW_ORIGIN
          value: "*"
        # Configuración LDAP
        - name: LDAP_HOST
          value: "aulasync-ldap"
        - name: LDAP_PORT
          value: "389"
        - name: LDAP_BASE_DN
          value: "dc=aulasync,dc=work,dc=gd"
        - name: LDAP_BIND_DN
          value: "cn=admin,dc=aulasync,dc=work,dc=gd"
        - name: LDAP_BIND_PASSWORD
          value: "admin"