apiVersion: v1
kind: Service
metadata:
  name: aulasync-back
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: backend